import{a as h,i as n,S as y}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=a(e);fetch(e.href,s)}})();const L="https://pixabay.com/api/",b="45057307-b447de7416eadb33be54d4a0d",S=400;async function f(t,r){const a={key:b,q:t,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r};try{return(await h.get(L,{params:a})).data}catch(i){i.response.status===S&&n.error({message:`Request error: ${i}`,position:"topRight"})}}const v=document.querySelector(".gallery");function B({webformatURL:t,largeImageURL:r,tags:a,likes:i,views:e,comments:s,downloads:l}){return`<li class="gallery-item"> 
    <figure class="sign">
      <a href="${r}">
        <img class="list-img" src="${t}" alt="${a}" title="" width="360" height="200"/>
      </a>
      <figcaption class="title-img">
        <ul class="figcaption">
          <li class="figcaption-item">Likes<p class="counter">${i}</p></li>
          <li class="figcaption-item">Views<p class="counter">${e}</p></li>
          <li class="figcaption-item">Comments<p class="counter">${s}</p></li>
          <li class="figcaption-item">Downloads<p class="counter">${l}</p></li>
        </ul>
      </figcaption>
    </figure>
  </li>`}function q(t){return t.map(B).join("")}function m(t){const r=q(t);v.innerHTML+=r}const o={btnSearch:document.querySelector(".btn-search"),form:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul.gallery"),loadBtn:document.querySelector(".load-btn")};let d=1,c="",p=new y(".gallery a");o.form.addEventListener("submit",async t=>{try{if(o.loadBtn.classList.remove("hiddenBtn"),t.preventDefault(),c=o.input.value.trim(),c===""){n.error({title:"Error",message:"Please enter a search query"});return}o.ul.innerHTML="",d=1,g();const r=await f(c,d);u(),r.hits.length===0?(n.error({title:"No results",message:"No images found. Please try a different query."}),o.loadBtn.classList.add("hidden")):(m(r.hits),p.refresh(),r.hits.length<15?o.loadBtn.classList.add("hidden"):o.loadBtn.classList.remove("hidden"))}catch{u(),n.error({title:"Error",message:"Something went wrong."})}});o.loadBtn.addEventListener("click",async()=>{d+=1,g();const t=await f(c,d);u(),t.hits.length===0?(o.loadBtn.classList.add("hiddenBtn"),n.info({title:"No more results",message:"We're sorry, but you've reached the end of search results."})):(m(t.hits),p.refresh(),t.hits.length<15&&(o.loadBtn.classList.add("hiddenBtn"),n.info({title:"No more results",message:"We're sorry, but you've reached the end of search results."}))),w()});function w(){window.scrollTo({top:document.body.scrollHeight,behavior:"smooth"})}function g(){o.loadBtn.insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>')}function u(){document.querySelector(".loader").remove()}
//# sourceMappingURL=commonHelpers.js.map
