import{S as u,i as a}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const f=document.querySelector(".gallery");function m({webformatURL:r,largeImageURL:o,tags:i,likes:s,views:e,comments:t,downloads:n}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${o}"><img class="list-img" src="${r}" alt="${i}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${t}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${n}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function p(r){return r.map(m).join("")}function d(r){const o=p(r);f.innerHTML=o}function g(r){document.querySelector(".form").insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>');const i=new URLSearchParams({key:"44959261-ea439a2adbf8f7e5770dfe1a3",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20});return fetch(`https://pixabay.com/api/?${i}`).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const l={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul"),loader:document.querySelector(".loader")};l.formEl.addEventListener("submit",r=>{r.preventDefault(),l.ul.innerHTML="",l.input.value.trim()?(c(),g(l.input.value.trim()).then(i=>{if(i.total!==0){d(i.hits);let s=new u(".gallery a");c(),s.refresh()}else a.error({message:"Image is not found",position:"topRight"})}).catch(i=>console.log(i)).finally(()=>{h(),l.input.value=""})):a.error({message:"Please fill in the input field",position:"topRight"})});function c(){l.loader.style.display="block"}function h(){l.loader.style.display="none"}
//# sourceMappingURL=commonHelpers.js.map
