import{s as c,i as a}from"./assets/vendor-5c957d73.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&s(n)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function s(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();async function u(r){document.querySelector(".form").insertAdjacentHTML("afterend",'<div id="loader" class="loader"></div>');const i=new URLSearchParams({key:"45057307-b447de7416eadb33be54d4a0d",q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:20}),e=await fetch(`https://pixabay.com/api/?${i}`);if(!e.ok)throw new Error(e.status);return await e.json()}const f=document.querySelector(".gallery");function m({webformatURL:r,largeImageURL:o,tags:i,likes:s,views:e,comments:t,downloads:n}){return`<li class="gallery-item> 
    <figure class="sign">
        <a href="${o}"><img class="list-img" src="${r}" alt="${i}" title="" width="360" height="200"/></a><span class="title-img">
        <figcaption class="title-img"><ul class="figcaption">
      <li class="figcaption-item">Likes<p class="counter">${s}</p></li>
      <li class="figcaption-item">Views<p class="counter">${e}</p></li>
      <li class="figcaption-item">Comments<p class="counter">${t}</p></li>
      <li class="figcaption-item">Downloads<p class="counter">${n}</p></li>
    </ul></figcaption>
    </figure>
   </li>`}function p(r){return r.map(m).join("")}function d(r){const o=p(r);f.innerHTML=o}const l={btnSubEl:document.querySelector(".btn-search"),formEl:document.querySelector(".form"),input:document.querySelector("input"),ul:document.querySelector("ul")};l.formEl.addEventListener("submit",r=>{r.preventDefault(),l.ul.innerHTML="",l.input.value.trim()?(u(l.input.value.trim()).then(i=>{i.total!==0?(d(i.hits),new c(".gallery a").refresh()):a.error({message:"Image is not found",position:"topRight"})}).catch(i=>console.log(i)).finally(()=>{document.querySelector(".loader").remove()}),l.input.value=""):a.error({message:"Please fill in the input field :c",position:"topRight"})});
//# sourceMappingURL=commonHelpers.js.map
